name: Github Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18.13.0
          cache: npm

      - name: Build
        run: |
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.4.0
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          branch: gh-pages
          folder: out
